set encoding=utf-8
filetype plugin indent on

" APPEARANCE
set viminfo^=!
set t_Co=16
syntax on
colorscheme eldar
set novisualbell
set showcmd
set showmode
set ruler
set cmdheight=1
set laststatus=2
set number
set cursorline
set display+=lastline
set linebreak
set breakindent

" COMPLETION
set wildmode=longest,list,full
set wildmenu

" EXTERNAL
set autoread
set autowriteall
set clipboard=unnamedplus

" FORMATTING
set shiftround
set expandtab
set smarttab
set autoindent
set cpo+=J

" INPUT
let mapleader=","
let maplocalleader=","
set backspace=indent,eol,start
nnoremap Q <nop>
nnoremap <Leader><Leader> :<Up><CR>
nnoremap <ESC><ESC> :nohlsearch<CR><C-l>
inoremap jk <ESC>`^<C-l>

" SEARCHING
set ignorecase
set smartcase
set incsearch
set showmatch
set hlsearch
