set encoding=utf-8
filetype plugin indent on

" APPEARANCE
set viminfo^=!
set t_Co=16
syntax on
set novisualbell
set showcmd
set showmode
set ruler
set cmdheight=1
set laststatus=2
set number
set display+=lastline
set linebreak
set cursorline
colorscheme eldar

if has('breakindent')
        set breakindent
end

" COMPLETION
set wildmode=longest,list,full
set wildmenu

" EXTERNAL
set autoread
set autowriteall
set clipboard^=unnamed,unnamedplus

" FORMATTING
set shiftround
set expandtab
set smarttab
set autoindent
set cpo+=J

" INPUT
let mapleader=","
let maplocalleader=","
set backspace=indent,eol,start
nnoremap Q <nop>
nnoremap <Leader>. :cd %:p:h<CR>:pwd<CR>
nnoremap <Leader>.. :cd ..<CR>:pwd<CR>
nnoremap <Leader>w :w<CR>
nnoremap <Space> za
nnoremap <Leader><Leader> <C-^>
nnoremap <C-l> :nohlsearch<CR><C-l>
inoremap jk <ESC>`^<C-l>

" SEARCHING
set ignorecase
set smartcase
set incsearch
set showmatch
set hlsearch
runtime! local.vim macros/matchit.vim
